AWSTemplateFormatVersion: '2010-09-09'
Description: s3 static file 

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: my-static-website-12ww2
      WebsiteConfiguration: 
        IndexDocument: index.html
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: false
      Tags:
        - Key: key
          Value: value

  BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref S3Bucket
        PolicyDocument: 
          Version: '2012-10-17'
          Statement: 
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: '*'
              Action: s3:GetObject
              Resource: !Sub 'arn:aws:s3:::${S3Bucket}/*'
